// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// Defines values for GeofenceAlertMessageEvent.
const (
	GeofenceEntry GeofenceAlertMessageEvent = "geofence_entry"
)

// Defines values for HealthChecks.
const (
	Down HealthChecks = "down"
	Up   HealthChecks = "up"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GeofenceAlertMessage Format pesan RabbitMQ (exchange `fleet.events`, queue `geofence_alerts`).
// Didokumentasikan sebagai referensi; tidak dikembalikan oleh endpoint mana pun.
type GeofenceAlertMessage struct {
	Event     GeofenceAlertMessageEvent `json:"event"`
	Location  Location                  `json:"location"`
	Timestamp int64                     `json:"timestamp"`
	VehicleId string                    `json:"vehicle_id"`
}

// GeofenceAlertMessageEvent defines model for GeofenceAlertMessage.Event.
type GeofenceAlertMessageEvent string

// GeofenceEvent defines model for GeofenceEvent.
type GeofenceEvent struct {
	Event      string   `json:"event"`
	GeofenceId string   `json:"geofence_id"`
	Location   Location `json:"location"`

	// ReceivedAt Waktu worker memproses event
	ReceivedAt time.Time `json:"received_at"`
	Timestamp  int64     `json:"timestamp"`
	VehicleId  string    `json:"vehicle_id"`
}

// Health defines model for Health.
type Health struct {
	Checks map[string]HealthChecks `json:"checks"`
	Status HealthStatus            `json:"status"`
}

// HealthChecks defines model for Health.Checks.
type HealthChecks string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Location defines model for Location.
type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// VehicleLocation Lokasi kendaraan. Bentuk yang sama dipakai sebagai payload MQTT
// pada topik `/fleet/vehicle/{vehicle_id}/location`.
type VehicleLocation struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`

	// Timestamp Unix epoch (detik)
	Timestamp int64  `json:"timestamp"`
	VehicleId string `json:"vehicle_id"`
}

// VehicleID defines model for VehicleID.
type VehicleID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListVehicleGeofenceEventsParams defines parameters for ListVehicleGeofenceEvents.
type ListVehicleGeofenceEventsParams struct {
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetVehicleHistoryParams defines parameters for GetVehicleHistory.
type GetVehicleHistoryParams struct {
	// Start Awal rentang waktu (unix epoch, detik, inklusif)
	Start int64 `form:"start" json:"start"`

	// End Akhir rentang waktu (unix epoch, detik, inklusif). Harus >= start.
	End int64 `form:"end" json:"end"`

	// Limit Jumlah maksimum data yang dikembalikan
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Status service dan dependensinya
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// Daftar event geofence kendaraan yang sudah diproses worker
	// (GET /vehicles/{vehicle_id}/geofence-events)
	ListVehicleGeofenceEvents(c *gin.Context, vehicleId VehicleID, params ListVehicleGeofenceEventsParams)
	// Mendapatkan riwayat lokasi dalam rentang waktu tertentu
	// (GET /vehicles/{vehicle_id}/history)
	GetVehicleHistory(c *gin.Context, vehicleId VehicleID, params GetVehicleHistoryParams)
	// Mendapatkan lokasi terakhir kendaraan
	// (GET /vehicles/{vehicle_id}/location)
	GetVehicleLocation(c *gin.Context, vehicleId VehicleID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListVehicleGeofenceEvents operation middleware
func (siw *ServerInterfaceWrapper) ListVehicleGeofenceEvents(c *gin.Context) {

	var err error

	// ------------- Path parameter "vehicle_id" -------------
	var vehicleId VehicleID

	err = runtime.BindStyledParameterWithOptions("simple", "vehicle_id", c.Param("vehicle_id"), &vehicleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vehicle_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVehicleGeofenceEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVehicleGeofenceEvents(c, vehicleId, params)
}

// GetVehicleHistory operation middleware
func (siw *ServerInterfaceWrapper) GetVehicleHistory(c *gin.Context) {

	var err error

	// ------------- Path parameter "vehicle_id" -------------
	var vehicleId VehicleID

	err = runtime.BindStyledParameterWithOptions("simple", "vehicle_id", c.Param("vehicle_id"), &vehicleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vehicle_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVehicleHistoryParams

	// ------------- Required query parameter "start" -------------

	if paramValue := c.Query("start"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument start is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "start", c.Request.URL.Query(), &params.Start)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter start: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "end" -------------

	if paramValue := c.Query("end"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument end is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "end", c.Request.URL.Query(), &params.End)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter end: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVehicleHistory(c, vehicleId, params)
}

// GetVehicleLocation operation middleware
func (siw *ServerInterfaceWrapper) GetVehicleLocation(c *gin.Context) {

	var err error

	// ------------- Path parameter "vehicle_id" -------------
	var vehicleId VehicleID

	err = runtime.BindStyledParameterWithOptions("simple", "vehicle_id", c.Param("vehicle_id"), &vehicleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vehicle_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVehicleLocation(c, vehicleId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/vehicles/:vehicle_id/geofence-events", wrapper.ListVehicleGeofenceEvents)
	router.GET(options.BaseURL+"/vehicles/:vehicle_id/history", wrapper.GetVehicleHistory)
	router.GET(options.BaseURL+"/vehicles/:vehicle_id/location", wrapper.GetVehicleLocation)
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleGeofenceEventsRequestObject struct {
	VehicleId VehicleID `json:"vehicle_id"`
	Params    ListVehicleGeofenceEventsParams
}

type ListVehicleGeofenceEventsResponseObject interface {
	VisitListVehicleGeofenceEventsResponse(w http.ResponseWriter) error
}

type ListVehicleGeofenceEvents200JSONResponse []GeofenceEvent

func (response ListVehicleGeofenceEvents200JSONResponse) VisitListVehicleGeofenceEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleGeofenceEvents400JSONResponse struct{ BadRequestJSONResponse }

func (response ListVehicleGeofenceEvents400JSONResponse) VisitListVehicleGeofenceEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleGeofenceEvents500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVehicleGeofenceEvents500JSONResponse) VisitListVehicleGeofenceEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleHistoryRequestObject struct {
	VehicleId VehicleID `json:"vehicle_id"`
	Params    GetVehicleHistoryParams
}

type GetVehicleHistoryResponseObject interface {
	VisitGetVehicleHistoryResponse(w http.ResponseWriter) error
}

type GetVehicleHistory200JSONResponse []VehicleLocation

func (response GetVehicleHistory200JSONResponse) VisitGetVehicleHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleHistory400JSONResponse struct{ BadRequestJSONResponse }

func (response GetVehicleHistory400JSONResponse) VisitGetVehicleHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleHistory500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVehicleHistory500JSONResponse) VisitGetVehicleHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleLocationRequestObject struct {
	VehicleId VehicleID `json:"vehicle_id"`
}

type GetVehicleLocationResponseObject interface {
	VisitGetVehicleLocationResponse(w http.ResponseWriter) error
}

type GetVehicleLocation200JSONResponse VehicleLocation

func (response GetVehicleLocation200JSONResponse) VisitGetVehicleLocationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleLocation400JSONResponse struct{ BadRequestJSONResponse }

func (response GetVehicleLocation400JSONResponse) VisitGetVehicleLocationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleLocation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVehicleLocation404JSONResponse) VisitGetVehicleLocationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleLocation500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVehicleLocation500JSONResponse) VisitGetVehicleLocationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Status service dan dependensinya
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Daftar event geofence kendaraan yang sudah diproses worker
	// (GET /vehicles/{vehicle_id}/geofence-events)
	ListVehicleGeofenceEvents(ctx context.Context, request ListVehicleGeofenceEventsRequestObject) (ListVehicleGeofenceEventsResponseObject, error)
	// Mendapatkan riwayat lokasi dalam rentang waktu tertentu
	// (GET /vehicles/{vehicle_id}/history)
	GetVehicleHistory(ctx context.Context, request GetVehicleHistoryRequestObject) (GetVehicleHistoryResponseObject, error)
	// Mendapatkan lokasi terakhir kendaraan
	// (GET /vehicles/{vehicle_id}/location)
	GetVehicleLocation(ctx context.Context, request GetVehicleLocationRequestObject) (GetVehicleLocationResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVehicleGeofenceEvents operation middleware
func (sh *strictHandler) ListVehicleGeofenceEvents(ctx *gin.Context, vehicleId VehicleID, params ListVehicleGeofenceEventsParams) {
	var request ListVehicleGeofenceEventsRequestObject

	request.VehicleId = vehicleId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListVehicleGeofenceEvents(ctx, request.(ListVehicleGeofenceEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVehicleGeofenceEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListVehicleGeofenceEventsResponseObject); ok {
		if err := validResponse.VisitListVehicleGeofenceEventsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVehicleHistory operation middleware
func (sh *strictHandler) GetVehicleHistory(ctx *gin.Context, vehicleId VehicleID, params GetVehicleHistoryParams) {
	var request GetVehicleHistoryRequestObject

	request.VehicleId = vehicleId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVehicleHistory(ctx, request.(GetVehicleHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVehicleHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVehicleHistoryResponseObject); ok {
		if err := validResponse.VisitGetVehicleHistoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVehicleLocation operation middleware
func (sh *strictHandler) GetVehicleLocation(ctx *gin.Context, vehicleId VehicleID) {
	var request GetVehicleLocationRequestObject

	request.VehicleId = vehicleId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVehicleLocation(ctx, request.(GetVehicleLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVehicleLocation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVehicleLocationResponseObject); ok {
		if err := validResponse.VisitGetVehicleLocationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ3VbcyBF+lTrKXsCJmBEGe2Fy9gIH/5AAa2O8SdYQUzNdSG2pW6K7BZ7lzG0eII+Y",
	"J8npbo1+ZsSAjZ3snRqk+v2q6que22CSiyKXJI0ORrdBgQoFGVLu9AslfJLRwb49MNITxQvDcxmMguNc",
	"5AqKPOOawxAO9iElyVAhyiAM6DOKIqNgFDzffLK1/fd//BqEAbffFWiSIAwkCvvfa6/gI2dBGCi6Krki",
	"FoyMKikM9CQhgVa1wM+HJGOTBKMnURgILufHzdBKNKSs7H9+2Nv4FTd+izZ2N87/+EMQBmZaWDXaKC7j",
	"YDabWS26yKUm5+BzZCd0VZI29jTJpSHpHrEoMj5B6+zwk7Ye3zZO2TeZlXtw/Mve4cH+x72TV++PXhyf",
	"BmEgSGuMvVJUBkSpDYwJMtIaTIIScgV0VWIGJgeSLJi1Pf1B0WUwCv4wbNIy9P/VwxdK5co70c3Fm3nS",
	"wHCGKVxjxhmsCa4xk1MEb8lZGUVbZFUCGizhMlcCDWjMMFm3VhxIG0fMvJ6vi8fpi5PjvcNOHHglFjSp",
	"a1JA3o1He/1XcqajhAUNVvZxbl7mpWRf5cbxz6cfX/78/ni/40eFVZgjGmRu4NIpebwz+2iwqaAqj4wb",
	"EmWKMpjVGhxs6wwVKi9IGe7R7M1vedTxZKEWWq61v1jh5XI5tWv2g1ffiD2v38/Hn2hirMpXlF+SnNBe",
	"RsocNfq7wXjpkVmQRgknOB5zc/QW1ujzJEEZE1xcZkRmQNc2thchXJVUElzElfCPaKXri/XBmdznLE9L",
	"QdKg5ilK0DTGGDkouiRFUvM/1cFOSYwxc2/lGSW2UoqcSwMCJUJRysGZ7W3dmDsj3IMshY1CbQVJo6at",
	"KDSBz3IPwfvQcjh/bxYGhgvSBkXRSdfmj5tPo2hr++mzMPD17Avu2XaTLVsdsa+KVrvtJL3VpFenuNOv",
	"vestd9pWrsr+i3nM7gplbdhCMHtiWb+x6JPIJergG0Vf0YT4NbGPaJbh+jdMTQk3uUpJgSBRqFyThnl4",
	"6rwwNLRhI9Rn1e8wv+3Q3pPtboT6cv+aMLMDe6lnJTRJ3RMyxq1gzN50YVEVVmnVsPxG9tZUq4uLK2PD",
	"5N4vcm1iZQX5s3LdRFz586zHUG3QlB3FeWoVU6yQEetRvhDDSkA4d60vGoctDHbjkaHhplzo4xvPBk+i",
	"nZ02lvJynLWAJEsx9hjIchkvS9iMng12ujC6S8SCO7VBbdF9PlVkse1at04O8xQ1b6bcAJ6TNGUKU5Qx",
	"aBQIjBeYIq+7dIHTLEcGR29PT89kgQzB5AVP4WLoZsCwAuzwtkHubDiH6EVfw/7SAAv8zIUFwq5nnv6w",
	"YU/fIPa19M2djnh3XJLfaRLd4L6X/DNQkU8SWGNkeLrepuEr+0itdfMre8pKev4FDacXaquHipXH5WW+",
	"HJCTF+9OYe/NAWiuDQk3xD+RIAmohAXSqUKpP2GKyuDgTJ5Jx8EyD1JLvRQXCBndoHH4gwZ+Z/Jh+IO1",
	"CsAj8FMFLhaq5GI9PJOMay4KlJASvPEN693bwxAyzEpgWKABxjG1Q0WQ/SNvuAnjMMYbTAZn0o1VmHdt",
	"WFPIeKnhaQRi3dIbrriwKmpGdQehOpMMJTA+xgnOxxpDxe/iWb7KMj4hqR3yq+Vuvk8EYVCqLBgFiTHF",
	"aOjCkyW5Nh7SxsHppbUAjlBibJNkbOoCiz6lfT43B9Egsl/kBUkseDAKtgbRYCtwG2DianuYuCnzm32O",
	"yY1qW/ou0gcsGAWvyFSDaGERfBJFD1gVHkbyKw09LP8diRKBUUGSWe4JmhJ0YXgabf0P9O+xjnbXdz37",
	"rQyx868UAtXUWusGmVuq+ITAgaL+WE7RlibG2pbxu6mtseDcCpjXhO4WxRw1Gx5lrRT1bEJjUqgx87Cr",
	"IOisFSTjXOpS6DvhGJ5JTQmXcYxNmXDJLTUbl6lxBB+zUvmq/s+//t0qOnesC8QevHaP8S6YDrk2VTl3",
	"mK12kGzuUT70p6t5Zdjcs8zCW39PclWSI7xVLWVccMu+GgQwusQyM3a8RN2mvvWkM1iiKFrd42fnjywG",
	"u6bq+1DZJf8N80KlcNoH1oV2ZkiNUZWQ0ZgnwMqstEK2val9imuXhq1bHldqD/ikexfSrYt9vDSoPL9v",
	"7GuWd09nSoaJ5TN+GfAoalXMPBwraybh2uRW5x21ckQybpbW+egiGaOEi9atz+QnqIdo/ReS7CIExktV",
	"mhSl7fqq6gkFZlzGkKHAATznGVZdwg5AhgbD7rbsUghprnMZ9xXKK5rXyevKoccVyEJTu8EMlN3wZQw3",
	"bhdbK2s2FIJjQyFwmWal5pc9vChyJdJXdi6GK68m72ZTUU+lLRufJlx9ifUDeI2q1NVt3k/+bm+w7NPu",
	"7u5uv08k2ff06C+lyDABgam2Xzm8eFS1MROEX9Hm7u1z36fR1ZH90N4e6pWhRfobpt9i6m3u3SbTDYO2",
	"QVwQ/ONuj+Bnm/2Cd+4UfB5+aZte3OIe0KhP+A1O0cz7T/M7wP+pPx9ZAwq0TQ1U1zaGGYqFcjOkbPbL",
	"VnOugqBXNuf2PdJdZHMxmo/oe4/E7neD7gNJ6RKulnFU3Q8YUui64mOBtB1t3/9J/UPBt0Zedqc3/Tiz",
	"gtzPFx4Y3dC8zrVpX5P4Ef/uBuOYFLw/gLU/I2PTEFg+sVzZWa5pvV69hj2D8xBlrEsZ251wTvJfcQlr",
	"XshGJWSQX5NSnNFgiiJbv3ObG+1EO5HDaeXe7T35Za36LEh9wgylW4KbQFVjoY7TshMLLHEl96qk1dRr",
	"WZpfncDd3DUfVNvN7Hz23wAAAP//XrO2zC8dAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
