// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type GeofenceEvent struct {
	ID         int64     `json:"id"`
	MessageID  string    `json:"message_id"`
	VehicleID  string    `json:"vehicle_id"`
	GeofenceID string    `json:"geofence_id"`
	EventType  string    `json:"event_type"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	Timestamp  int64     `json:"timestamp"`
	ReceivedAt time.Time `json:"received_at"`
}

type InboxMessage struct {
	Consumer    string    `json:"consumer"`
	MessageID   string    `json:"message_id"`
	EventType   string    `json:"event_type"`
	ProcessedAt time.Time `json:"processed_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Exchange      string          `json:"exchange"`
	RoutingKey    string          `json:"routing_key"`
	Headers       json.RawMessage `json:"headers"`
	Payload       json.RawMessage `json:"payload"`
	DedupKey      string          `json:"dedup_key"`
	Status        string          `json:"status"`
	Attempts      int32           `json:"attempts"`
	LastError     sql.NullString  `json:"last_error"`
	AvailableAt   time.Time       `json:"available_at"`
	CreatedAt     time.Time       `json:"created_at"`
	PublishedAt   sql.NullTime    `json:"published_at"`
}

type VehicleGeofencePresence struct {
	VehicleID  string    `json:"vehicle_id"`
	GeofenceID string    `json:"geofence_id"`
	EnteredTs  int64     `json:"entered_ts"`
	EnteredAt  time.Time `json:"entered_at"`
}

type VehicleLocation struct {
	ID        int64     `json:"id"`
	VehicleID string    `json:"vehicle_id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	Timestamp int64     `json:"timestamp"`
	CreatedAt time.Time `json:"created_at"`
}
