// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, exchange, routing_key, headers, payload, attempts, created_at
FROM outbox_events
WHERE status = 'pending' AND available_at <= now()
ORDER BY created_at, id
LIMIT $1::int
FOR UPDATE SKIP LOCKED
`

type ClaimPendingOutboxEventsRow struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Exchange      string          `json:"exchange"`
	RoutingKey    string          `json:"routing_key"`
	Headers       json.RawMessage `json:"headers"`
	Payload       json.RawMessage `json:"payload"`
	Attempts      int32           `json:"attempts"`
	CreatedAt     time.Time       `json:"created_at"`
}

// Dijalankan relay di dalam transaksi. SKIP LOCKED membuat beberapa
// instance relay aman berjalan paralel tanpa mengirim event yang sama.
func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, batchSize int32) ([]ClaimPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingOutboxEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingOutboxEventsRow{}
	for rows.Next() {
		var i ClaimPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Exchange,
			&i.RoutingKey,
			&i.Headers,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxEventsByStatus = `-- name: CountOutboxEventsByStatus :many
SELECT status, count(*)::bigint AS total
FROM outbox_events
GROUP BY status
ORDER BY status
`

type CountOutboxEventsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountOutboxEventsByStatus(ctx context.Context) ([]CountOutboxEventsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countOutboxEventsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOutboxEventsByStatusRow{}
	for rows.Next() {
		var i CountOutboxEventsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProcessedInboxMessages = `-- name: DeleteProcessedInboxMessages :execrows
DELETE FROM inbox_messages
WHERE processed_at < $1::timestamptz
`

// Housekeeping. Retensi harus lebih lama dari kemungkinan redelivery.
func (q *Queries) DeleteProcessedInboxMessages(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProcessedInboxMessages, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePublishedOutboxEvents = `-- name: DeletePublishedOutboxEvents :execrows
DELETE FROM outbox_events
WHERE status = 'published'
    AND published_at < $1::timestamptz
`

func (q *Queries) DeletePublishedOutboxEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePublishedOutboxEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enterGeofence = `-- name: EnterGeofence :execrows
INSERT INTO vehicle_geofence_presence (vehicle_id, geofence_id, entered_ts)
VALUES ($1, $2, $3)
ON CONFLICT (vehicle_id, geofence_id) DO NOTHING
`

type EnterGeofenceParams struct {
	VehicleID  string `json:"vehicle_id"`
	GeofenceID string `json:"geofence_id"`
	EnteredTs  int64  `json:"entered_ts"`
}

// 1 baris = kendaraan baru masuk -> tulis outbox event geofence_entry.
// 0 baris = sudah di dalam sejak sebelumnya -> tidak ada event.
func (q *Queries) EnterGeofence(ctx context.Context, arg EnterGeofenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enterGeofence, arg.VehicleID, arg.GeofenceID, arg.EnteredTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const exitGeofence = `-- name: ExitGeofence :execrows
DELETE FROM vehicle_geofence_presence
WHERE vehicle_id = $1 AND geofence_id = $2
`

type ExitGeofenceParams struct {
	VehicleID  string `json:"vehicle_id"`
	GeofenceID string `json:"geofence_id"`
}

// 1 baris = kendaraan baru keluar (bisa dipakai untuk event geofence_exit).
func (q *Queries) ExitGeofence(ctx context.Context, arg ExitGeofenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, exitGeofence, arg.VehicleID, arg.GeofenceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestVehicleLocation = `-- name: GetLatestVehicleLocation :one
SELECT vehicle_id, latitude, longitude, timestamp
FROM vehicle_loctions
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestVehicleLocationRow struct {
	VehicleID string  `json:"vehicle_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Timestamp int64   `json:"timestamp"`
}

func (q *Queries) GetLatestVehicleLocation(ctx context.Context, vehicleID string) (GetLatestVehicleLocationRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestVehicleLocation, vehicleID)
	var i GetLatestVehicleLocationRow
	err := row.Scan(
		&i.VehicleID,
		&i.Latitude,
		&i.Longitude,
		&i.Timestamp,
	)
	return i, err
}

const insertGeofenceEvent = `-- name: InsertGeofenceEvent :execrows
INSERT INTO geofence_events (
    message_id, vehicle_id, geofence_id, event_type, latitude, longitude, timestamp
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (message_id) DO NOTHING
`

type InsertGeofenceEventParams struct {
	MessageID  string  `json:"message_id"`
	VehicleID  string  `json:"vehicle_id"`
	GeofenceID string  `json:"geofence_id"`
	EventType  string  `json:"event_type"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	Timestamp  int64   `json:"timestamp"`
}

// Dipanggil worker dalam transaksi yang sama dengan InsertInboxMessage.
func (q *Queries) InsertGeofenceEvent(ctx context.Context, arg InsertGeofenceEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertGeofenceEvent,
		arg.MessageID,
		arg.VehicleID,
		arg.GeofenceID,
		arg.EventType,
		arg.Latitude,
		arg.Longitude,
		arg.Timestamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInboxMessage = `-- name: InsertInboxMessage :execrows
INSERT INTO inbox_messages (consumer, message_id, event_type)
VALUES ($1, $2, $3)
ON CONFLICT (consumer, message_id) DO NOTHING
`

type InsertInboxMessageParams struct {
	Consumer  string `json:"consumer"`
	MessageID string `json:"message_id"`
	EventType string `json:"event_type"`
}

// Langkah pertama worker di dalam transaksi.
// 0 baris = pesan sudah pernah diproses -> commit & ack tanpa memproses ulang.
func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertInboxMessage, arg.Consumer, arg.MessageID, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :execrows
INSERT INTO outbox_events (
    aggregate_type, aggregate_id, event_type,
    exchange, routing_key, headers, payload, dedup_key
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8
)
ON CONFLICT (dedup_key) DO NOTHING
`

type InsertOutboxEventParams struct {
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Exchange      string          `json:"exchange"`
	RoutingKey    string          `json:"routing_key"`
	Headers       json.RawMessage `json:"headers"`
	Payload       json.RawMessage `json:"payload"`
	DedupKey      string          `json:"dedup_key"`
}

// Dipanggil dalam transaksi ingest. dedup_key contoh:
// 'geofence_entry:B1234XYZ:monas:1715003456'
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Exchange,
		arg.RoutingKey,
		arg.Headers,
		arg.Payload,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertVehicleLocation = `-- name: InsertVehicleLocation :execrows
INSERT INTO vehicle_loctions (vehicle_id, latitude, longitude, timestamp)
VALUES ($1, $2, $3, $4)
ON CONFLICT (vehicle_id, timestamp) DO NOTHING
`

type InsertVehicleLocationParams struct {
	VehicleID string  `json:"vehicle_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Timestamp int64   `json:"timestamp"`
}

// 0 baris = duplikat (pesan MQTT QoS 1 terkirim ulang) -> lewati geofence.
func (q *Queries) InsertVehicleLocation(ctx context.Context, arg InsertVehicleLocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertVehicleLocation,
		arg.VehicleID,
		arg.Latitude,
		arg.Longitude,
		arg.Timestamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listGeofenceEventsByVehicle = `-- name: ListGeofenceEventsByVehicle :many
SELECT id, message_id, vehicle_id, geofence_id, event_type, latitude, longitude, timestamp, received_at
FROM geofence_events
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT $2::int
`

type ListGeofenceEventsByVehicleParams struct {
	VehicleID string `json:"vehicle_id"`
	MaxRows   int32  `json:"max_rows"`
}

func (q *Queries) ListGeofenceEventsByVehicle(ctx context.Context, arg ListGeofenceEventsByVehicleParams) ([]GeofenceEvent, error) {
	rows, err := q.db.QueryContext(ctx, listGeofenceEventsByVehicle, arg.VehicleID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeofenceEvent{}
	for rows.Next() {
		var i GeofenceEvent
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.VehicleID,
			&i.GeofenceID,
			&i.EventType,
			&i.Latitude,
			&i.Longitude,
			&i.Timestamp,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleGeofencePresence = `-- name: ListVehicleGeofencePresence :many
SELECT geofence_id, entered_ts, entered_at
FROM vehicle_geofence_presence
WHERE vehicle_id = $1
ORDER BY geofence_id
`

type ListVehicleGeofencePresenceRow struct {
	GeofenceID string    `json:"geofence_id"`
	EnteredTs  int64     `json:"entered_ts"`
	EnteredAt  time.Time `json:"entered_at"`
}

func (q *Queries) ListVehicleGeofencePresence(ctx context.Context, vehicleID string) ([]ListVehicleGeofencePresenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleGeofencePresence, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleGeofencePresenceRow{}
	for rows.Next() {
		var i ListVehicleGeofencePresenceRow
		if err := rows.Scan(&i.GeofenceID, &i.EnteredTs, &i.EnteredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleLocationHistory = `-- name: ListVehicleLocationHistory :many
SELECT vehicle_id, latitude, longitude, timestamp
FROM vehicle_loctions
WHERE vehicle_id = $1
  AND timestamp BETWEEN $2::bigint AND $3::bigint
ORDER BY timestamp ASC
LIMIT $4::int
`

type ListVehicleLocationHistoryParams struct {
	VehicleID string `json:"vehicle_id"`
	StartTs   int64  `json:"start_ts"`
	EndTs     int64  `json:"end_ts"`
	MaxRows   int32  `json:"max_rows"`
}

type ListVehicleLocationHistoryRow struct {
	VehicleID string  `json:"vehicle_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Timestamp int64   `json:"timestamp"`
}

func (q *Queries) ListVehicleLocationHistory(ctx context.Context, arg ListVehicleLocationHistoryParams) ([]ListVehicleLocationHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleLocationHistory,
		arg.VehicleID,
		arg.StartTs,
		arg.EndTs,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleLocationHistoryRow{}
	for rows.Next() {
		var i ListVehicleLocationHistoryRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.Latitude,
			&i.Longitude,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET attempts     = attempts + 1,
    last_error   = $1::text,
    status       = CASE
                       WHEN attempts + 1 >= $2::int THEN 'failed'
                       ELSE 'pending'
                   END,
    available_at = now() + ($3::int * INTERVAL '1 second')
WHERE id = $4
`

type MarkOutboxEventFailedParams struct {
	LastError      string    `json:"last_error"`
	MaxAttempts    int32     `json:"max_attempts"`
	BackoffSeconds int32     `json:"backoff_seconds"`
	ID             uuid.UUID `json:"id"`
}

// Retry dengan backoff; setelah max_attempts status menjadi 'failed'.
// Di klausa SET, "attempts" selalu bernilai lama (sebelum update).
func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventFailed,
		arg.LastError,
		arg.MaxAttempts,
		arg.BackoffSeconds,
		arg.ID,
	)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET status       = 'published',
    attempts     = attempts + 1,
    published_at = now(),
    last_error   = NULL
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventPublished, id)
	return err
}

const requeueFailedOutboxEvents = `-- name: RequeueFailedOutboxEvents :execrows
UPDATE outbox_events
SET status       = 'pending',
    attempts     = 0,
    last_error   = NULL,
    available_at = now()
WHERE status = 'failed'
`

// Operasional: kirim ulang event yang gagal permanen setelah masalah diperbaiki.
func (q *Queries) RequeueFailedOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueFailedOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
