// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Dijalankan relay di dalam transaksi. SKIP LOCKED membuat beberapa
	// instance relay aman berjalan paralel tanpa mengirim event yang sama.
	ClaimPendingOutboxEvents(ctx context.Context, batchSize int32) ([]ClaimPendingOutboxEventsRow, error)
	CountOutboxEventsByStatus(ctx context.Context) ([]CountOutboxEventsByStatusRow, error)
	// Housekeeping. Retensi harus lebih lama dari kemungkinan redelivery.
	DeleteProcessedInboxMessages(ctx context.Context, before time.Time) (int64, error)
	DeletePublishedOutboxEvents(ctx context.Context, before time.Time) (int64, error)
	// 1 baris = kendaraan baru masuk -> tulis outbox event geofence_entry.
	// 0 baris = sudah di dalam sejak sebelumnya -> tidak ada event.
	EnterGeofence(ctx context.Context, arg EnterGeofenceParams) (int64, error)
	// 1 baris = kendaraan baru keluar (bisa dipakai untuk event geofence_exit).
	ExitGeofence(ctx context.Context, arg ExitGeofenceParams) (int64, error)
	GetLatestVehicleLocation(ctx context.Context, vehicleID string) (GetLatestVehicleLocationRow, error)
	// Dipanggil worker dalam transaksi yang sama dengan InsertInboxMessage.
	InsertGeofenceEvent(ctx context.Context, arg InsertGeofenceEventParams) (int64, error)
	// Langkah pertama worker di dalam transaksi.
	// 0 baris = pesan sudah pernah diproses -> commit & ack tanpa memproses ulang.
	InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) (int64, error)
	// Dipanggil dalam transaksi ingest. dedup_key contoh:
	// 'geofence_entry:B1234XYZ:monas:1715003456'
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error)
	// 0 baris = duplikat (pesan MQTT QoS 1 terkirim ulang) -> lewati geofence.
	InsertVehicleLocation(ctx context.Context, arg InsertVehicleLocationParams) (int64, error)
	ListGeofenceEventsByVehicle(ctx context.Context, arg ListGeofenceEventsByVehicleParams) ([]GeofenceEvent, error)
	ListVehicleGeofencePresence(ctx context.Context, vehicleID string) ([]ListVehicleGeofencePresenceRow, error)
	ListVehicleLocationHistory(ctx context.Context, arg ListVehicleLocationHistoryParams) ([]ListVehicleLocationHistoryRow, error)
	// Retry dengan backoff; setelah max_attempts status menjadi 'failed'.
	// Di klausa SET, "attempts" selalu bernilai lama (sebelum update).
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	// Operasional: kirim ulang event yang gagal permanen setelah masalah diperbaiki.
	RequeueFailedOutboxEvents(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
